fossasia/meilix-generator

docs/installation/my_token.md
=> Updated Readme.md

app.py
- Removed the unnecessary parameter passed in Resource function as the default is already set equal to that param only
- Added docstring for functions in the code
=> Removed unnecessary parameters & Added comments

app.py, static/email.css, templates/build.html
removes Yield output 
- added email html page and css
- edited app.py for removing yield output and add email page
Fixes #81 #29
=> remove static and add email

.github/CONTRIBUTING.md
This should clear out doubt about how to contribute.
- add review policy
- prevent stagnation
Fixes #86
=> describe the review policy

templates/build.html
the email css location in the html was wrong
- fixed the location of css in build.html
=> css location fix

templates/index.html
Added Logo at index page
-Added Logo 
Fixes #70
=> Added meilix-generator icon

app.py
Fixed the indentation errors.
Fixes #95
=> Fixed Indentation Style

templates/index.html
e issue number that is fixed by this PR (In the form Fixes #123) -->
Fixes #89
=> Tooltips for webapp

travis_script_1.sh
Reverts fossasia/meilix-generator#101
=> Revert "Delete travis_script_1.sh"

travis_script_1.sh, travis_tokens
- changed generator branch from xeon-zolt/meilix to fossasia/meilix
=> Shift to fossasia branch from xeon-zolt

manifest.yml
added a manifest.yml file for deployment to bluemix
Fixes # shifting to meilix.org
https://meilix-generator.au-syd.mybluemix.net/
=> deployment to bluemix

templates/index.html
=> Break the line when text length exeeds span width fixed issue#97

static/css/menu.css, templates/index.html
- a css for logo position in menu.css
- meilix generator logo position
=> modified the position of meilix generator logo

README.md, dockerfile, docs/installation/docker.md
it makes testing easier and faster now user just need to make changes and create a docker image to test instead of setting up the environment. and one can deploy docker file directly to Heroku too.
- dockerfile
- documentation to use it
=> Docker container for meilix generator

.gitignore
Fixes an issue from #108. 
Removes an extra entry from .gitignore for vscode.
=> Remove an extra entry from .gitignore

templates/index.html
Fixes https://github.com/fossasia/meilix-generator/issues/139
=> Checkbox for selecting packages

templates/index.html
Fixes https://github.com/fossasia/meilix-generator/issues/139
=> Added radio on and off options

.travis.yml, runtime.txt
=> Update of Python Runtime

templates/index.html
=> Selection of multiple options at the same time

templates/index.html
=> Solve the build button bug

app.py, scripts/chromium-package.sh, templates/index.html
=> Updating index for scripting

scripts/vlc-package.sh
https://github.com/fossasia/meilix-generator/issues/151
=> VLC script 

app.py
=> Getting all the variables in app.py

templates/index.html
=> Added email validation

templates/index.html
=> Replaced owncloud with nextcloud

templates/index.html
=> Added switch replacing radio button

templates/index.html
- aligning text and boxes in the center.
- created space between two separate lines.
Fixes #
=> improving appearance

templates/index.html
=> Added recommended size pop-up

templates/index.html
=> Alphanumeric characters Info

templates/index.html
=> fixing issue #171 and #167

templates/index.html
=> Corrected email appearance error

templates/index.html
This PR provides a description help bar view the need of filling of the option.
- A help bar which pop-up while one click on it.
- It gets closed after clicking on a blank screen.
Fixes #166
=> Added help section

templates/index.html
Fixes #184 #183 
[https://rpotter.herokuapp.com/](url)
=> removing help button and putting * on compulsory option

static/js/email_noti.js, static/js/functions.js, templates/index.html
-drop-down solved
-
-
Fixes #194
=> dropdown fixed

static/js/email_noti.js, templates/index.html
- created a function in email.js for onclick command 
- inserted a question sign image in front of upload text
Fixes #198 
heroku link: https://rpotter.herokuapp.com/
=> creating a question sign in front of upload

scripts/chromium-package.sh, scripts/vlc-package.sh
Removed script from webapp
- We will locally include script in Meilix repo
- There is no need to download script from one repo to another
Fixes #202
=> Removed scripts from the webapp

templates/index.html
=> Toggle for 64 bit

static/js/functions.js
=> dropdown menu fix

static/css/style.css, templates/index.html
As suggested by @mariobehling, the following are the resolves:
* The tweaks are in the right hand side and the toggle are in the left hand side
* The build button is now square
* The width and other distances are now equal for all sections
Fixes #208
=> Solves issue #208

static/css/style.css, static/js/email_noti.js, templates/index.html
This solves the issue of showing system information from dialogs as suggested by @mariobehling , and hence solves issue#207
- In some UI I could not apply the scroll event as it is was not executing 
- I need suggestions for the style
Fixes #207 
I will upload the gif with the changes soon
=> Show info on scroll over: fixes issue #207

static/css/email.css, static/css/menu.css, templates/index.html
Have added fa-fa icons for all text fields. Initially only the email input field had the fa-fa icon but now all the input fields have fa-fa icons. The name input field has address book type of fa-fa icon which depicts the name of the distribution. The search engine input field has a microscope signifying we are trying to search something. 
Fixes #215
=> fixes issue #215

static/css/email.css, static/css/menu.css
The PR solves the issue of different font-family in text-boxes and labels. I have solved the issue by making the font-family of the whole body along with the labels and text-boxes to be Helvetica. If Helvetica is not present then I have kept Verdana as the fall back font.
Fixes #201
=> fixes issue #201

static/css/style.css, templates/index.html
Initially the page did not have required meta tags and ogp tags for a proper SEO. So in this PR I have added the required meta tags along with the ogps. This will make the ranking of our site better and during searches our site's ranking will be better.
-Added meta tags
-Added ogp tags
Fixes #218
=> fixes issue #218

templates/index.html
Solves #229 temporarily, needs a better 
- Show labels all the time
Fixes #229
=> Fix UI issues (temporary)

dockerfile
- [ x ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ x ] There is a corresponding issue for this pull request.
- [ x ] My branch is up-to-date with the Upstream `master` branch.
- [ x ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added necessary documentation (if appropriate)
reduced size of Docker container
- using alpine as a base now
=> shorten the docker file size

templates/index.html
=> fixes #234

templates/index.html
=> fixes #235

templates/index.html
Dropbox added as an option in the second table as it was previously there but due to some changes was missing from the second table.
Fixes #242
=> fixes #242

static/css/style.css, templates/index.html
This adds a upload similar to upload wallpaper option for zip,  and tar.gz files in your local machine
Size of file should be less than 4Mb
-A button and an input similar to upload wallpaper option
-Function for checking the size of the file
-
Fixes #238
=> Added option for uploading zip, tar.gz file- (Solves issue #238)

app.py, templates/404.html
- Improving UI for 404 page
Fixes #276
=> Fixes #276 Improving the 404 page using standard homepage templates 

templates/index.html
The alignment issue is solved in the current build
-Restructuring of code
-
-
Fixes #291
=> Fix alignment issue-(Solves- #291)

templates/includes/_navbar.html
This removes the unwanted link which redirects to the same page.
-Removed link which redirects to the same page.
Fixes #307
=> Solved #307

static/css/style.css
There is unplesant white space in the navbar
Changes the navbar size to make it larger and reduce whitespace.
Fixes #315
=> Removed Empty Space in Navbar

static/css/style.css
I fixed issue #311. I added some styles to navbar to harmonise the logo and the top bar as the issue. 
And I added a hover effect.
- Change the color of nav bar.
- Add a hover effect to the navbar.
Fixes #311 
Thank you!
@tabesin Can you have a look?
=> Fixed #311 Added styles to navbar

static/css/email.css, templates/build.html, templates/layout.html
This PR makes sure that build html looks better on mobile phones. Had to close the previous pr
- added email.css link to layout.html
- added width for images in build.html
- add margin in email.css
Fixes #301 
Had to close my previous PR #304 as there were some issues with it.
The same changes can be viewed on https://rahulkumaran-meilix.herokuapp.com
=> Optimise build.html in /output route for mobiles

.travis.yml, pr_deploy.sh
Fixes #338
-Surge has been added for auto deployment of the PR's.
=> Added surge auto deployment

static/css/menu.css, static/css/style.css, templates/includes/_navbar.html
Fixes #326
-Navbar menu which was appearing to be stretched has now been fixed.
**Screenshots**
=> Navbar menu fixed

app.py
Previously the app was having configuration of the uploads directory only
- Configuration for wallpapers, logos, zip files is added in the app
-
-
Fixes #335 
The scope of this pr is to add  configuration for various folder according to different uploading options 
This pr is a part of the pr #303 ; beacause it contained a lot of changes I am trying to break the changes with multiple pr's
=> This adds config for seperate directories for the various uploading options -(Solves- #335)

templates/index.html
Enables bootstrap tooltip on input boxes.
Edited index.html 
Fixes #344
=> Enabling Bootstrap tooltip to input boxes

templates/index.html
The misalignmnet of the buttons was due to the missing btn-block class,
it has now been added to fix the misalignment.
Fixes #264
Misalignment of buttons has been fixed.
**Screenshots**
=> Misalignment of buttons has been fixed.

static/css/style.css, templates/includes/_footer.html, templates/index.html
This PR changes the functioning to be displayed when the user hovers over the element, not when the user scrolls.
- Makes it so that the functioning is only displayed when the user hovers over the element
- Prevents the appearance of the functioning from distorting the layout of the app
- Cleans up a lot of messy code
Fixes #288 
Preview Link: https://polar-beyond-34005.herokuapp.com/
=> Fix Continuous Display of Functioning

static/css/style.css
It resolves the bug on hovering the last element.
-[Preview link](https://afternoon-mountain-42157.herokuapp.com/)
Fixes #366
=> Removed unwanted text on hovering.

app.py
The uploaded files can now be downloaded for travis to be included in the ISO
- The files are all renamed to a general file name
- The route for the file is added using app.route
- 
Fixes #373
=> The uploaded files is accessible now- (Solves -#373)

README.md
This solves the `Page not found` error on clicking the link given for my_token.md file in README.md   
- Fixing the link for my_token.md given in the Readme file
-
-
Fixes #378
=> Corrected my_token link for readme file - (Solves - #378)

pr_deploy.sh
The auto_deployment script for surge was failing because of the `project not found error`
- The script has been rectified for the error
-
-
Fixes #375
=> This solves automatic deployment for surge - (Solves- #375)

static/css/style.css, templates/includes/_header.html
Fixed contrast of the text, header, and footer a little bit. 
Fixes #387 
**Screenshots**
=> Fixed Contrast

static/images/logo_meilix.svg, templates/includes/_header.html
Fixes #385 
Logo updated
**Screenshots**
=> Logo Updated

templates/includes/_footer.html, templates/includes/_header.html
Fixes #383
Added `rel=noopener` for cross-origin links.
=> Cross origin destination links were unsafe

docs/installation/docker.md
modifies the docker docs
- modifies the docker docs
-
-
Fixes #392
=> Modify the docker docs

.vscode/settings.json, app.py
This adds a new variables features that just dumps all the generator packages into a json array 
This will make it easier to transmit the generator variables into the build server 
Fixes #394
=> Added json variable `features` for generator packages - (Solves- #394)

app.py, build.py, requirements.in, requirements.txt
This adds alternative python script for the triggering of travis script 
- Addition of alternative script build.py for the triggering of travis build which contains a method to send the trigger request
- The method is called from app.py with the required arguments
-
Fixes #124
=> Travis trigger script in python added - (Solves- #124)

docs/installation/my_token.md
Added documentation for setting up your local heroku app development to trigger travis builds for local meilix forks
Fixes #402
=> Added documentation for managing heroku config vars - (Solves- #402)

.vscode/settings.json, build.py
This solves the `unbound variable` when the recipe array will be in a meilix build 
- Dumping the recipe array into a representation that can be used in the build server
-
-
Fixes #405
=> Solved unbound-variable error for the generator-packages - (Solves- #405)

app.py, templates/index.html
This adds information for the features toggles, and stores them in a features array
This features array is then send to the build server.
- Adding name, value pair to the feature.
- Storing the name-value pair in a feature array.
-
Fixes #400
=> Added post information for feature toggles to add various features to meilix - (Solves- #400)

app.py, build.py, templates/index.html
This adds an option for choice of processor(64bit or 32bit) using the bit support toggle 
Now, we can add an option on the build scripts in the main repo for 32bit or 64bit support
- Adding a name,value pair for the 64bit support toggle 
- Storing the value of the toggle in a variable named processor
- The processor variable is then sent to the build server
Fixes #409
=> This adds option for choice of processor using the 64bit support toggle - (Solves- #409)

app.py, build.py
This sends the feature array from the generator webapp to the meilix build server,
- Dumping the feature array to a json string
- 
-
Fixes #414
=> This sends the features array to the meilix build server - (Solves- #414)

app.py, build.py
Display of error code on a bad trigger request
- Added code to send an error message to the front-end
Fixes #416
=> added code to display error message on bad trigger requests

app.py, build.py
sending wallpaper files to Travis 
- Send wallpaper using transfer.sh
- If transfer.sh fails, send using 0x0.st
- if both fails, upload files to host server(subject race around)
Fixes #398
=> using 3rd party services to send wallpaper to Travis(meilix)

app.py
handling wallpaper upload code when no wallpaper is uploaded
- returning blank URL parameter if no wallpaper is selected
Fixes #428 , #427
=> handling the case when no wallpaper is uploaded

app.py, build.py
sending logo to Travis
- Send wallpaper using transfer.sh
- If transfer.sh fails, send using 0x0.st
- if both fails, upload files to host server(subject to race around condition)
link to deployment - https://meilix-gen.herokuapp.com/
Fixes #426
=> changing the way logo is sent to travis

app.py, build.py
This sends the theme from the webapp to the build server
- Changes in app.py: Setting the theme variable to dark on user choice
- Changes in build.py: Sending the theme to build server
-
Fixes #431 
Test Deployment: 
https://meilix-generator-433.herokuapp.com/
=> This sends the theme to the build server

templates/index.html
This adds an option to the user to choose between dark theme or light theme 
This resolves the frontend part,a pr for the backend part will be opened shortly
- Adding a toggle for the light or dark theme
-
-
Fixes #431 
Test deployment
https://meilix-generator-432.herokuapp.com
=> Adding option for dark and light theme for the meilix ISO - (Solves -#431)

docs/installation/heroku.md, templates/index.html
I have just added and update the changes in index.html
=> Corrected minor changes to index.html

templates/includes/_header.html, templates/index.html
Corrected some minor typos and minor changes in templates/index.html file.
=> Corrected some minor typos and minor changes in templates/index.html

templates/includes/_header.html
Made logo appear same on both, header and tab.
Fixes #441
=> Made logo same of both header and tab
